apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: nodeinfo
spec:
  name: nodeinfo
  replicas: 2
  handler: node main.js
  image: functions/nodeinfo:burner
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "15"
  environment:
    output: "verbose"
    debug: "true"
